apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  {{ .Values.secret.keys.username }}: {{ .Values.secret.values.username }}
    {{ .Values.secret.keys.password }}: {{ .Values.secret.values.password }}
    {{ .Values.secret.keys.dbname }}: {{ .Values.secret.values.dbname }}
