#name: Deploy to Kubernetes
#on:
#  workflow_run:
#    workflows: ["Build and Push Image"]
#    types:
#      - completed
#
#jobs:
#  deploy:
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Update Kubernetes deployment
#        run: |
#          kubectl set image deployment/my-app my-container=yourname/app:latest -n your-namespace
#          kubectl rollout status deployment/my-app -n your-namespace
